import type { Metadata } from "next";
import { Jost, DM_Sans } from "next/font/google";
import "./globals.css";

const jost = Jost({
  variable: "--font-jost"
});

const dmSans = DM_Sans();

export const metadata: Metadata = {
  title: "Whatsapp Automation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} ${dmSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
